using System.Windows; using System.Windows.Controls; using System.Windows.Threading; using HECUVoiceLab.Audio; using HECUVoiceLab.Presets; using HECUVoiceLab.Analysis; using Microsoft.Win32;
namespace HECUVoiceLab;
public partial class MainWindow:Window
{ readonly AudioEngine engine=new(); Preset current=PresetManager.HecuReference; readonly DispatcherTimer timer=new(){Interval=TimeSpan.FromMilliseconds(50)}; readonly Dictionary<string,Slider> sliders=new();
 public MainWindow(){InitializeComponent(); BuildSliders(); PresetCombo.ItemsSource=PresetManager.BuiltIns; PresetCombo.SelectedIndex=0; TargetText.Text="Peak -9.3 dBFS, RMS -20.8 dBFS, active RMS -18 to -19 dBFS, silence -85 dBFS; bands 15.8/37.6/17.3/19.1/5.1/1.6/~0%."; Refresh(); timer.Tick+=(s,e)=>{InputMeter.Value=engine.InputLevel;OutputMeter.Value=engine.OutputLevel;ClipText.Text=engine.Clip?"Clip: LIMITING":"Clip: OK";ClipText.Foreground=engine.Clip?System.Windows.Media.Brushes.OrangeRed:System.Windows.Media.Brushes.LightGreen;StatusText.Text=engine.Status;}; timer.Start();}
 void BuildSliders(){ Add(RadioPanel,"InputGainDb","Input Gain dB",-24,24); Add(RadioPanel,"OutputGainDb","Output Gain dB",-24,12); Add(RadioPanel,"DryWet","Dry/Wet %",0,100); Add(RadioPanel,"GateThresholdDb","Gate Threshold dBFS",-70,-20); Add(RadioPanel,"GateHardness","Gate Hardness %",0,100); Add(RadioPanel,"GateHoldMs","Gate Hold ms",0,200); Add(RadioPanel,"GateReleaseMs","Gate Release ms",20,300); Add(RadioPanel,"HighPassHz","High-Pass Hz",60,250); Add(RadioPanel,"LowPassHz","Low-Pass Hz",3000,8000); Add(RadioPanel,"HelmetLowMidDb","Helmet Low-Mid dB",-6,8); Add(RadioPanel,"RadioPresenceDb","Radio Presence dB",-6,8); Add(RadioPanel,"HarshEdgeDb","Harsh Edge dB",-4,5); Add(CrunchPanel,"EffectiveSampleRate","Effective Sample Rate",8000,24000); Add(CrunchPanel,"BitDepth","Bit Depth",6,16); Add(CrunchPanel,"CrunchMix","Crunch Mix %",0,100); Add(CrunchPanel,"AntiAliasSmoothness","Anti-Alias Smoothness %",0,100); Add(CompPanel,"CompressorThresholdDb","Compressor Threshold dBFS",-45,-10); Add(CompPanel,"CompressorRatio","Compressor Ratio",1,10); Add(CompPanel,"CompressorAttackMs","Compressor Attack ms",.5,20); Add(CompPanel,"CompressorReleaseMs","Compressor Release ms",30,300); Add(CompPanel,"MakeupGainDb","Makeup Gain dB",0,18); Add(CompPanel,"GritDrive","Grit Drive %",0,100); Add(CompPanel,"LimiterCeilingDb","Limiter Ceiling dBFS",-12,-1); var cb=new CheckBox{Content="Output Safety Limiter",IsChecked=true,Margin=new Thickness(4)}; cb.Checked+=ControlChanged; cb.Unchecked+=ControlChanged; CompPanel.Children.Add(cb); Add(ChopPanel,"ChopAmount","Chop Amount %",0,100); Add(ChopPanel,"TransientBite","Transient Bite %",0,100); Add(ChopPanel,"EndCutTightness","End Cut Tightness %",0,100); Add(ChopPanel,"RadioClickAmount","Radio Click Amount %",0,100); Add(ChopPanel,"RadioNoiseAmount","Radio Noise Amount %",0,100); }
 void Add(Panel p,string prop,string label,double min,double max){var t=new TextBlock(); var s=new Slider{Minimum=min,Maximum=max,Tag=prop}; s.ValueChanged+=(a,b)=>{t.Text=$"{label}: {s.Value:0.##}"; ControlChanged(a,b);}; p.Children.Add(t); p.Children.Add(s); sliders[prop]=s;}
 void LoadPreset(Preset p){current=p.Clone(); BypassBox.IsChecked=current.Bypass; foreach(var kv in sliders){var val=(float)(typeof(Preset).GetProperty(kv.Key)!.GetValue(current)!); kv.Value.Value=val;} engine.ApplyPreset(current);} void Pull(){foreach(var kv in sliders)typeof(Preset).GetProperty(kv.Key)!.SetValue(current,(float)kv.Value.Value); current.Bypass=BypassBox.IsChecked==true; engine.ApplyPreset(current);} void ControlChanged(object? s, RoutedEventArgs e)=>Pull();
 void Refresh(){InputCombo.ItemsSource=DeviceManager.Inputs(); OutputCombo.ItemsSource=DeviceManager.Outputs(); if(InputCombo.Items.Count>0)InputCombo.SelectedIndex=0; if(OutputCombo.Items.Count>0)OutputCombo.SelectedIndex=0; RoutingText.Text=$"Selected input: {InputCombo.Text}\nSelected output: {OutputCombo.Text}";} void Refresh_Click(object s,RoutedEventArgs e)=>Refresh();
 void StartStop_Click(object s,RoutedEventArgs e){ if(engine.IsRunning){engine.Stop();StartStopButton.Content="START";} else {try{engine.Start(((AudioDeviceInfo)InputCombo.SelectedItem).Index,((AudioDeviceInfo)OutputCombo.SelectedItem).Index);StartStopButton.Content="STOP";}catch(Exception ex){MessageBox.Show(ex.Message,"Audio device error");}}}
 void PresetCombo_SelectionChanged(object s,SelectionChangedEventArgs e){ if(PresetCombo.SelectedItem is Preset p)LoadPreset(p);} void Reset_Click(object s,RoutedEventArgs e){PresetCombo.SelectedIndex=0;LoadPreset(PresetManager.HecuReference);} void AnalyzeEmbedded_Click(object s,RoutedEventArgs e)=>Show(AudioAnalyzer.EmbeddedTarget,AudioAnalyzer.EmbeddedTarget);
 void LoadReference_Click(object s,RoutedEventArgs e){var d=new OpenFileDialog{Filter="Audio files|*.wav;*.mp3|WAV|*.wav|MP3|*.mp3"}; if(d.ShowDialog()==true){try{Show(AudioAnalyzer.AnalyzeFile(d.FileName),AudioAnalyzer.EmbeddedTarget);}catch(Exception ex){MessageBox.Show("Could not decode file. WAV is supported; MP3 requires Windows Media Foundation codec. "+ex.Message);}}}
 void Show(AnalysisResult a,AnalysisResult t){var sc=MatchScorer.Score(a,t); AnalysisText.Text=$"HECU Match Score: {sc.Score}/100\nDuration {a.Duration:0.00}s, {a.SampleRate} Hz, {a.Channels} ch, mono {a.EffectivelyMono}\nPeak {a.PeakDb:0.0} dBFS, RMS {a.RmsDb:0.0}, Active {a.ActiveRmsDb:0.0}, Silence {a.SilenceFloorDb:0.0}\nBands: {string.Join(", ",a.Bands.Select(x=>x.ToString("0.0")))}\nRolloffs: {string.Join(", ",a.Rolloffs.Select(x=>x.ToString("0")))} Hz\nHints:\n{sc.Hints}";}
 protected override void OnClosed(EventArgs e){engine.Dispose();base.OnClosed(e);} }
