using NAudio.Wave; namespace HECUVoiceLab.Analysis;
public sealed record AnalysisResult(double Duration,int SampleRate,int Channels,bool EffectivelyMono,double PeakDb,double RmsDb,double ActiveRmsDb,double SilenceFloorDb,double[] Bands,double[] Rolloffs);
public static class AudioAnalyzer
{ public static AnalysisResult EmbeddedTarget => new(28.75,44100,2,true,-9.3,-20.8,-18.5,-85,new[]{15.8,37.6,17.3,19.1,5.1,1.6,0.1},new[]{624d,1658,2961,3725,5114});
 public static AnalysisResult AnalyzeFile(string path){ using var r=new AudioFileReader(path); var data=new List<float>(); var buf=new float[r.WaveFormat.SampleRate*r.WaveFormat.Channels]; int n; while((n=r.Read(buf,0,buf.Length))>0) for(int i=0;i<n;i+=r.WaveFormat.Channels){float s=0; for(int c=0;c<r.WaveFormat.Channels;c++)s+=buf[i+c]; data.Add(s/r.WaveFormat.Channels);} return Analyze(data.ToArray(),r.WaveFormat.SampleRate,r.WaveFormat.Channels);}
 public static AnalysisResult Analyze(float[] samples,int sr,int ch){ if(samples.Length==0)return new(0,sr,ch,true,-120,-120,-120,-120,new double[7],new double[5]); double peak=samples.Max(x=>Math.Abs(x)); double rms=Math.Sqrt(samples.Average(x=>x*x)); var active=samples.Where(x=>Math.Abs(x)>0.02f).ToArray(); double ar=active.Length>0?Math.Sqrt(active.Average(x=>x*x)):0; var quiet=samples.OrderBy(x=>Math.Abs(x)).Take(Math.Max(1,samples.Length/10)).Select(x=>(double)x*x).Average(); var bands=EstimateBands(samples,sr); var rolls=EstimateRolloffs(samples,sr); return new((double)samples.Length/sr,sr,ch,true,Db(peak),Db(rms),Db(ar),Db(Math.Sqrt(quiet)),bands,rolls);}
 static double Db(double v)=>20*Math.Log10(Math.Max(v,1e-6));
 static double[] EstimateBands(float[] s,int sr){ double[] edges={100,300,800,1600,3400,5500,11025,24000}, e=new double[7]; int step=Math.Max(64,sr/100); for(int i=0;i+step<s.Length;i+=step){ for(int k=0;k<7;k++){ double sum=0; for(int n=0;n<step;n++) sum+=s[i+n]*Math.Sin(2*Math.PI*((edges[k]+edges[k+1])/2)*n/sr); e[k]+=sum*sum; }} var total=e.Sum()+1e-9; return e.Select(x=>x/total*100).ToArray();}
 static double[] EstimateRolloffs(float[] s,int sr){ var b=EstimateBands(s,sr); double[] centers={200,550,1200,2500,4450,8300,14000}; double cum=0; var res=new double[5]; double[] pct={50,75,90,95,98}; int j=0; for(int i=0;i<b.Length&&j<5;i++){cum+=b[i]; while(j<5&&cum>=pct[j])res[j++]=centers[i];} while(j<5)res[j++]=centers[^1]; return res;}
}
