using System.Runtime.InteropServices; using HECUVoiceLab.Dsp; using HECUVoiceLab.Presets; using NAudio.Wave; using NAudio.Wave.SampleProviders;
namespace HECUVoiceLab.Audio;
public sealed class AudioEngine:IDisposable
{ WaveInEvent? input; WaveOutEvent? output; BufferedWaveProvider? buffer; Preset preset=PresetManager.HecuReference; readonly object gateLock=new(); readonly RadioEq eq=new(); readonly NoiseGate gate=new(); readonly TacticalChop chop=new(); readonly SampleRateReducer srr=new(); readonly BitCrusher crusher=new(); readonly Compressor comp=new(); readonly Saturator sat=new(); readonly Limiter limiter=new(); readonly RadioClickNoise clicks=new(); float sr=48000; public float InputLevel{get;private set;} public float OutputLevel{get;private set;} public bool Clip{get;private set;} public string Status{get;private set;}="Stopped"; public bool IsRunning=>input!=null;
 public void ApplyPreset(Preset p){lock(gateLock){preset=p.Clone(); Configure();}}
 void Configure(){ eq.Configure(sr,preset); gate.Configure(sr,preset); chop.Configure(sr,preset); srr.Configure(sr,preset); crusher.Configure(preset); comp.Configure(sr,preset); sat.Configure(preset); limiter.Configure(preset); clicks.Configure(preset); }
 public void Start(int inDev,int outDev){Stop(); sr=48000; Configure(); var fmt=WaveFormat.CreateIeeeFloatWaveFormat((int)sr,2); buffer=new BufferedWaveProvider(fmt){BufferDuration=TimeSpan.FromMilliseconds(120),DiscardOnBufferOverflow=true}; output=new WaveOutEvent{DeviceNumber=outDev,DesiredLatency=60}; output.Init(buffer); input=new WaveInEvent{DeviceNumber=inDev,WaveFormat=fmt,BufferMilliseconds=20}; input.DataAvailable+=OnData; input.RecordingStopped+=(s,e)=>Status=e.Exception?.Message??"Stopped"; output.Play(); input.StartRecording(); Status="Running: 20 ms capture / ~60 ms output"; }
 void OnData(object? s, WaveInEventArgs e){ if(buffer==null)return; var outBytes=new byte[e.BytesRecorded]; var inSpan=MemoryMarshal.Cast<byte,float>(e.Buffer.AsSpan(0,e.BytesRecorded)); var outSpan=MemoryMarshal.Cast<byte,float>(outBytes); float inPk=0,outPk=0; lock(gateLock){ for(int i=0;i<inSpan.Length;i+=2){ float dry=(inSpan[i]+(i+1<inSpan.Length?inSpan[i+1]:inSpan[i]))*.5f; inPk=Math.Max(inPk,Math.Abs(dry)); float y=dry*MathF.Pow(10,preset.InputGainDb/20); if(!preset.Bypass){ y=gate.Process(y); y=chop.Process(y,gate.IsOpen); if(chop.EdgeEvent)clicks.Trigger(); y=eq.Process(y); var reduced=srr.Process(y); var crushed=crusher.Process(reduced); y=y*(1-preset.CrunchMix/100)+crushed*(preset.CrunchMix/100); y=comp.Process(y); y=sat.Process(y); y=clicks.Process(y); y=eq.Process(y); if(preset.SafetyLimiter)y=limiter.Process(y);} y*=MathF.Pow(10,preset.OutputGainDb/20); y=dry*(1-preset.DryWet/100)+y*(preset.DryWet/100); Clip=limiter.Engaged||Math.Abs(y)>0.98f; outPk=Math.Max(outPk,Math.Abs(y)); outSpan[i]=y; if(i+1<outSpan.Length)outSpan[i+1]=y; }} InputLevel=inPk; OutputLevel=outPk; buffer.AddSamples(outBytes,0,outBytes.Length); }
 public void Stop(){ try{input?.StopRecording();}catch{} input?.Dispose(); output?.Stop(); output?.Dispose(); input=null; output=null; buffer=null; Status="Stopped"; }
 public void Dispose()=>Stop(); }
